import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
    },
    screens: {
      Fours: { max: '420px' },
      Four: { max: '400px' },
      Dmd: { min: '640px' },
      Dsm: { max: '640px' },
      Lsm: { max: '660px' },
      Fsm: { max: '500px' },
      Fmd: { min: '500px' },
      se: { max: '380px' },
      sse: '380px',
      ses: { min: '580px' },
      Mses: { max: '570px' },
      Msel: '570px',
      Mfes: { max: '578px' },
      sess: { max: '540px' },
      '2xl': { min: '1535px' },
      xl: { min: '1279px' },
      lg: { min: '768px' },
      Mlg: { max: '768px' },
      Hxl: { max: '1279px' },
      Hxls: { min: '1279px' },
      TRYNOW: { min: '1037px' },
      md: { min: '900px' },
      sm: { max: '900px' },
      Logosm: { max: '765px' },
      xss: { min: '480px' },
      xs: { max: '480px' },
      Sixmds: { min: '600px' },
      Sixmd: { max: '600px' },
      Bmd: { min: '770px' },
      Bsm: { max: '770px' },
      Blds: { min: '800px' },
      Bld: { max: '800px' },
      Bold: { min: '1150px' },
      Bolds: { max: '1150px' },
      Bxl: { max: '1200px' },
      Bxls: { min: '1200px' },
      Header: { min: '1300px' },
      Headers: { max: '1300px' },
      Header2: { min: '1400px' },
      Headers2: { max: '1400px' },
      Header3: { min: '1500px' },
      Headers3: { max: '1500px' },
      Header4: { min: '1600px' },
      Headers4: { max: '1600px' },
      Header5: { min: '1800px' },
      Headers5: { max: '1800px' },
      Header6: { min: '1930px' },
      Headers6: { max: '1930px' },
      FourT: { max: '410px' },
      smj: { max: '990px' },
      smjs: { min: '990px' },
      jsx: { max: '980px' },
      Bsd: { max: '780px' },
      Bsds: { min: '780px' },
      mmms: '360px'
    }
  },
  plugins: [],
};
export default config;
